# Camera
#
BOARD_USE_SAMSUNG_CAMERAFORMAT_NV21 := true
TARGET_KEEP_LEGACY_CAMERA_PACKAGE := true
TARGET_NEEDS_LEGACY_CAMERA_HAL1_DYN_NATIVE_HANDLE := true

PRODUCT_PACKAGES += \
	camera.universal7580
